/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DbcheckRouteImport } from './routes/dbcheck'
import { Route as BrowsercheckRouteImport } from './routes/browsercheck'
import { Route as AicheckRouteImport } from './routes/aicheck'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAhojRouteImport } from './routes/api/ahoj'

const DbcheckRoute = DbcheckRouteImport.update({
  id: '/dbcheck',
  path: '/dbcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowsercheckRoute = BrowsercheckRouteImport.update({
  id: '/browsercheck',
  path: '/browsercheck',
  getParentRoute: () => rootRouteImport,
} as any)
const AicheckRoute = AicheckRouteImport.update({
  id: '/aicheck',
  path: '/aicheck',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAhojRoute = ApiAhojRouteImport.update({
  id: '/api/ahoj',
  path: '/api/ahoj',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aicheck': typeof AicheckRoute
  '/browsercheck': typeof BrowsercheckRoute
  '/dbcheck': typeof DbcheckRoute
  '/api/ahoj': typeof ApiAhojRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aicheck': typeof AicheckRoute
  '/browsercheck': typeof BrowsercheckRoute
  '/dbcheck': typeof DbcheckRoute
  '/api/ahoj': typeof ApiAhojRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aicheck': typeof AicheckRoute
  '/browsercheck': typeof BrowsercheckRoute
  '/dbcheck': typeof DbcheckRoute
  '/api/ahoj': typeof ApiAhojRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aicheck' | '/browsercheck' | '/dbcheck' | '/api/ahoj'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aicheck' | '/browsercheck' | '/dbcheck' | '/api/ahoj'
  id: '__root__' | '/' | '/aicheck' | '/browsercheck' | '/dbcheck' | '/api/ahoj'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AicheckRoute: typeof AicheckRoute
  BrowsercheckRoute: typeof BrowsercheckRoute
  DbcheckRoute: typeof DbcheckRoute
  ApiAhojRoute: typeof ApiAhojRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dbcheck': {
      id: '/dbcheck'
      path: '/dbcheck'
      fullPath: '/dbcheck'
      preLoaderRoute: typeof DbcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browsercheck': {
      id: '/browsercheck'
      path: '/browsercheck'
      fullPath: '/browsercheck'
      preLoaderRoute: typeof BrowsercheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aicheck': {
      id: '/aicheck'
      path: '/aicheck'
      fullPath: '/aicheck'
      preLoaderRoute: typeof AicheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ahoj': {
      id: '/api/ahoj'
      path: '/api/ahoj'
      fullPath: '/api/ahoj'
      preLoaderRoute: typeof ApiAhojRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AicheckRoute: AicheckRoute,
  BrowsercheckRoute: BrowsercheckRoute,
  DbcheckRoute: DbcheckRoute,
  ApiAhojRoute: ApiAhojRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
